# baseURL = "https://examplesite.com/"
languageCode = "en-us"
title = "Joe"
theme = "bexar-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "/plugins/bootstrap/bootstrap.css"
  [[params.plugins.css]]
  URL = "/plugins/fontawesome/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "/plugins/animate/animate.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "/plugins/jQuery/jquery-2.0.0.min.js"
  [[params.plugins.js]]
  URL = "/plugins/bootstrap/bootstrap.bundle.min.js"
  [[params.plugins.js]]
  URL = "/plugins/wow/wow.min.js"



# navigation
[menu]

[params]
logo = "/images/logo.png"
logoAlt = "/images/logo-alt.png"
home = "Home"
# Meta data
description = ""
author = ""
# Google Analitycs
googleAnalitycsID = "Your ID"

# copyright
[params.copyright]
copyright = "The CV Name [www.weburl.com](https://www.weburl.com) "
